id = "aurbis"
name = "Aurbis Theme"
version = "0.0.1"
schema_version = 1
description = "A theme for Zed"
authors = ["Aymane Hlamnach <dara-@outlook.jp>"]
repository = "https://github.com/azuradara/aurbis-zed-theme"
